language: python
python:
      - "3.6"

install:
       - pip install -r mediumapp/requirements.txt


services:
  - mongodb
  
script: 
      - python mediumapp/app/app.py
      - python  mediumapp/app/unitestbasecase.py
