language: python
python:
- "2.7"
- "3.5"
- "3.7"
install:
- pip install -r mediumapp/requirements.txt
- pip install -e .
script: 
- python mediumapp/app/app.py
- python  mediumapp/app/unitestbasecase.py
